---
title: "Biofilm and Clump Replication"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, prompt = FALSE, eval = TRUE, 
                      warning = TRUE, comment=NA, cache = FALSE,
                      dpi = 300,
                      fig.width = 20, fig.height = 15)
library(tidyverse)
library(readr)
library(cowplot)
library(gghighlight)
```

## Biofilm

```{r, message=FALSE}
biofilm <- read_csv("C:/Users/katmu/Dropbox/Valdivia Lab/Projects/Replication of Biofilm and Clumping/Data for Analysis/biofilm_replicates_raw.csv")

biofilm$Column <- as.factor(biofilm$Column)
biofilm$Plate <- as.factor(biofilm$Plate)
```

```{r}
levels(biofilm$Plate)
```

```{r, warning=FALSE}
plates <- levels(biofilm$Plate)
all_biofilm <- "no data"

for (i in plates){
  #Calculate mean OD
  just_plate <- biofilm %>% filter(Plate == i) %>%
    group_by(Isolate) %>%
    mutate(mean_OD = mean(OD)) %>%
    distinct(Plate, .keep_all = TRUE) %>%
    as.data.frame() %>%
    select(c(Isolate, Plate, mean_OD))
  
  #Subtract blank from OD
  mean_blank <- as.numeric(just_plate[just_plate$Isolate == "blank", 3])
  blanked_plate <- just_plate %>%
  mutate(blanked_OD = mean_OD - mean_blank) %>% 
  filter(Isolate != "blank")
  
  #Calculate fold changes
  mean_BAA <- as.numeric(blanked_plate[blanked_plate$Isolate == "BAA-835", 3])
  mean_all <- mean(blanked_plate$mean_OD)
  df_plate <- blanked_plate %>%
    mutate(foldchange_BAA = mean_OD/mean_BAA, foldchange_mean = mean_OD/mean_all)
  
  #Set up dataframe of final output
  if(all_biofilm == "no data"){
    all_biofilm <- df_plate
  } else{
    all_biofilm <- rbind(all_biofilm, df_plate)
  }
}
```

```{r}
write.csv(all_biofilm, "C:/Users/katmu/Dropbox/Valdivia Lab/Projects/Replication of Biofilm and Clumping/Data for Analysis/biofilm_replicates.csv")
```

## Clumping

```{r, message=FALSE}
clump <- read_csv("C:/Users/katmu/Dropbox/Valdivia Lab/Projects/Replication of Biofilm and Clumping/Data for Analysis/clump_replicates_raw.csv")

clump$Column <- as.factor(clump$Column)
clump$Plate <- as.factor(clump$Plate)
```

```{r}
levels(clump$Plate)
```

```{r, warning=FALSE}
plates <- levels(clump$Plate)
all_clump <- "no data"
for (i in plates){
  just_plate <- clump %>% filter(Plate == i)
  
  #Subtract blank from OD
  blanks <- just_plate %>% filter(Isolate == "blank")
  mean_top <- mean(blanks$Top_OD)
  mean_bottom <- mean(blanks$Bottom_OD)
  blanked_plate <- just_plate %>%
    mutate(blanked_top = Top_OD - mean_top, blanked_bottom = Bottom_OD - mean_bottom) %>%
    filter(Isolate != "blank")
  blanked_plate$blanked_top <- abs(blanked_plate$blanked_top)
  
  #Remove samples that did not grow
  only_growth <- blanked_plate %>% filter(blanked_bottom > 0)
  
  #Calculate fold changes
  ratio_plate <- blanked_plate %>%
    mutate(BT_Ratio = blanked_bottom/blanked_top) %>%
    group_by(Isolate) %>%
    mutate(mean_BT = mean(BT_Ratio)) %>%
    distinct(Plate, .keep_all = TRUE) %>%
    as.data.frame() %>%
    select(c(Isolate, Plate, mean_BT))
  mean_BAA <- as.numeric(ratio_plate[ratio_plate$Isolate == "BAA-835", 3])
  mean_all <- mean(ratio_plate$mean_BT)
  df_plate <- ratio_plate %>%
    mutate(foldchange_BAA = mean_BT/mean_BAA, foldchange_mean = mean_BT/mean_all)
  
  if (all_clump == "no data"){
    all_clump <- df_plate
  } else {
    all_clump <- rbind(all_clump, df_plate)
  }
}
```

```{r}
write.csv(all_clump, "C:/Users/katmu/Dropbox/Valdivia Lab/Projects/Replication of Biofilm and Clumping/Data for Analysis/clump_replicates.csv")
```
